Update with okta-vue 3.0 - OKTA-340169
okta/samples-js-vue pull request #90
Opened 2020-10-27 21:44 UTC by shuowu-okta

2020-10-27 21:45 UTC, swiftone approved these changes

2020-12-07 17:16 UTC, aarongranick-okta commented on custom-login/src/components/Login.vue
> +          // To avoid redirect do not set "pkce" or "display" here. OKTA-335945
Let's update these samples to use latest SIW version and call `showSignInToGetTokens` then this workaround will not be necessary

2020-12-07 17:16 UTC, aarongranick-okta commented on okta-hosted-login/package.json
> +    "@okta/okta-vue": "file:.yalc/@okta/okta-vue",
don't forget to unyalc before merge!

2020-12-07 17:17 UTC, aarongranick-okta requested changes
Update to use latest SIW and remove yalc. Then ship it

2020-12-08 19:25 UTC, aarongranick-okta approved these changes

2020-12-08 19:28 UTC, closed without merging